apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-secret
spec:
  secretName: {{ .Release.Name }}-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
  commonName: {{ .Release.Name }}.k8.wildwidewest.xyz
  dnsNames:
  - {{ .Release.Name }}.k8.wildwidewest.xyz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - {{ .Release.Name }}.k8.wildwidewest.xyz