apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
  - hosts:
    - jenkins.k8.wildwidewest.xyz
    secretName: certificate
  rules:
  - host: jenkins.k8.wildwidewest.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080