apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /zpool-126262/WWWJENKINS
    server: "10.16.103.9"
  persistentVolumeReclaimPolicy: Recycle
