apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  capacity:
    storage: 8Gi
  claimRef:
    namespace: default
    name: {{ .Release.Name }}
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /zpool-126262/WWWJENKINS
    server: {{ .Values.nfs.server }}
  persistentVolumeReclaimPolicy: Recycle
