apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: default
    name: {{ .Release.Name }}
  nfs:
    path: /zpool-126262/WWWNEXUS/nexus
    server: {{ .Values.nfs.server }}
  persistentVolumeReclaimPolicy: Recycle