# Default values for ELK.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
  - kibana.k8.wildwidewest.xyz
  secretName: kibana-secret
  tls:
  - hosts:
    - kibana.k8.wildwidewest.xyz
    secretName: kibana-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

data:
  hooks:
    drain:
      enabled: False

kibana:
  service:
    externalPort: 80
  ingress:
    enabled: False
    hosts:
      - kibana.k8.wildwidewest.xyz
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
      kubernetes.io/ingress.class: nginx
    tls:
      - hosts:
          - kibana.k8.wildwidewest.xyz
        secretName: kibana-secret
    secretName: kibana
  env:
    ELASTICSEARCH_URL: http://elk-elasticsearch-client:9200
