# Default values for ELK.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  path: /
  hosts:
  - kibana.k8.wildwidewest.xyz
  secretName: kibana-secret
  tls:
  - hosts:
    - kibana.k8.wildwidewest.xyz
    secretName: kibana-secret

data:
  hooks:
    drain:
      enabled: False

filebeat:
  config:
    output:
      file:
        enabled: false
      elasticsearch:
        hosts: [ 'elk-elasticsearch-client:9200' ]
        pipeline: opus_log
    setup:
      kibana:
        host: elk-kibana:80

metricbeat:
  deployment:
    debug: true
    config:
      output.file:
        enabled: false
      output:
        elasticsearch:
          hosts: [ 'elk-elasticsearch-client:9200' ]
    modules:
      kubernetes:
        enabled: true
        config:
        - module: kubernetes
          hosts: ["elk-kube-state-metrics:8080"]
  daemonset:
    config:
      output.file:
        enabled: false
      output:
        elasticsearch:
          hosts: [ 'elk-elasticsearch-client:9200' ]
      setup:
        kibana:
          host: elk-kibana:80

elastalert:
  elasticsearch:
    host: elk-elasticsearch-client
    port: 9200

kibana:
  service:
    externalPort: 80
  ingress:
    enabled: False
    hosts:
    - kibana.k8.wildwidewest.xyz
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
      kubernetes.io/ingress.class: nginx
    tls:
    - hosts:
      - kibana.k8.wildwidewest.xyz
      secretName: kibana-secret
    secretName: kibana
  env:
    ELASTICSEARCH_URL: http://elk-elasticsearch-client:9200
#  plugins:
#    # set to true to enable plugins installation
#    enabled: true
#    # set to true to remove all kibana plugins before installation
#    reset: false
#    # Use <plugin_name,version,url> to add/upgrade plugin
#    values:
#      - elastalert-kibana-plugin,1.0.1,https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.1/elastalert-kibana-plugin-1.0.1-6.5.3.zip

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}