dependencies:
  - name: kube-state-metrics
    version: "0.12.1"
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: filebeat
    version: "1.1.1"
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: metricbeat
    version: "0.4.2"
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: elasticsearch
    version: "1.15.1"
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kibana
    version: "1.1.0"
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: elasticsearch-curator
    version: "1.0.1"
    repository: https://kubernetes-charts.storage.googleapis.com

