# Default values for ELK.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80


data:
  hooks:
    drain:
      enabled: False

filebeat:
  config:
    output:
      file:
        enabled: false
      elasticsearch:
        hosts: [ 'elasticstack-elasticsearch-client:9200' ]
        pipeline: opus_log
    setup:
      kibana:
        host: elasticstack-kibana:80

metricbeat:
  deployment:
    config:
      output.file:
        enabled: false
      output:
        elasticsearch:
          hosts: [ 'elasticstack-elasticsearch-client:9200' ]
    modules:
      kubernetes:
        enabled: true
        config:
        - module: kubernetes
          hosts: ["elasticstack-kube-state-metrics:8080"]
  daemonset:
    modules:
      kubernetes:
        enabled: false
    config:
      output.file:
        enabled: false
      output:
        elasticsearch:
          hosts: [ 'elasticstack-elasticsearch-client:9200' ]
      setup:
        kibana:
          host: elasticstack-kibana:80

heartbeat:
  config:
    output.file:
      enabled: false
    output:
      elasticsearch:
        hosts: [ 'elasticstack-elasticsearch-client:9200' ]

elasticsearch-curator:
  config:
    elasticsearch:
      hosts: [ 'elasticstack-elasticsearch-client' ]

kibana:
  service:
    externalPort: 80
  ingress:
    enabled: False
  env:
    ELASTICSEARCH_URL: http://elasticstack-elasticsearch-client:9200

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}